repos:
  - repo: local
    hooks:
      - id: check-ast
        name: check-ast
        entry: check-ast
        language: system
        types: [ python ]
        require_serial: true
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        require_serial: true
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        require_serial: true
        stages: [ commit, push, manual ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        require_serial: true
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [ cython, pyi, python ]
        args: [ "--filter-files" ]



  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
