"""Added initial table

Revision ID: bb49ad8bb420
Revises: 
Create Date: 2022-11-21 14:13:26.256281

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bb49ad8bb420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('created_on', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_on', sa.TIMESTAMP(), nullable=False),
                    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
                    sa.Column('username', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('username')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
