"""Added tweet table

Revision ID: c9b4fd9023b0
Revises: bb49ad8bb420
Create Date: 2022-11-22 05:49:07.297493

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c9b4fd9023b0'
down_revision = 'bb49ad8bb420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
                    sa.Column('created_on', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_on', sa.TIMESTAMP(), nullable=False),
                    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
                    sa.Column('tweet_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
                    sa.Column('creator', sa.String(length=50), nullable=False),
                    sa.Column('tweet_content', sa.String(length=200), nullable=False),
                    sa.ForeignKeyConstraint(['creator'], ['users.username'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('tweet_id')
                    )
    op.create_index(op.f('ix_tweets_creator'), 'tweets', ['creator'], unique=False)
    op.add_column('users', sa.Column('birthdate', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=False))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
                              existing_type=sa.VARCHAR(length=50), nullable=False,
                              existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'birthdate')
    op.drop_index(op.f('ix_tweets_creator'), table_name='tweets')
    op.drop_table('tweets')
    # ### end Alembic commands ###
