{{ if and .Values.certificates.hasCertManager (not .Values.certificates.skipTLSSecret)}}
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-ssl-secret
  namespace: {{.Values.namespace}}
type: kubernetes.io/tls
stringData:
  tls.key: {{required "You need an initial self signed certificate key" .Values.certificates.tlsInitialKey | b64enc | quote}}
  tls.crt: {{required "You need an initial self signed certificate" .Values.certificates.tlsInitialCert | b64enc | quote}}
{{end}}