# This workflow will build the docker image for the twitter cloneimportlib.metadata.version("mypackage")
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy FastAPI-Twitter-Clone Container

on:
  push:
      branches: main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GCP_GKE_CLUSTER }}
  GKE_ZONE: us-central1-c

jobs:

  build-fastapi-container:
    name: "Builds FastAPI container"
    runs-on: ubuntu-latest
    environment: GCP-GKE


    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup Artifact Repository
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Deploy FastAPI-Clone-Docker-Image
        run: helm install fastapi-twitter-clone deployment/fastapi-twitter-clone\
          --set namespace="production-fastapi-twitter-clone" \
          --set certificates.tlsInitialKey="$TLSINITIALKEY" \
          --set certificates.tlsInitialCert="$TLSINITIALCERT" \
          --set kibana.KIBANA_SERVER_URL="$KIBANA_SERVER_URL" \
          --set kibana.KIBANA_SECRET_TOKEN="$KIBANA_SECRET_TOKEN" \
          --set kibana.KIBANA_ENVIRONMENT="PRODUCTION-K8S" \
          --set DNS.subDomainPrefix="production.twitter-clone" \
          --set deployment.TAG="$(echo $(python deployment/read_version.py))"

