# This workflow will build the docker image for the twitter cloneimportlib.metadata.version("mypackage")
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy FastAPI-Twitter-Clone Container

on:
  workflow_dispatch:
  workflow_call:
  push:
env:
  PROJECT_ID: ${{ secrets.GCP_GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GCP_GKE_CLUSTER }}
  GKE_ZONE: us-central1-c

jobs:

  deploy-fastapi-container:
    name: "Deploys the container on GKE"
    runs-on: ubuntu-latest
    environment: GCP-GKE


    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup gcloud region
        run: gcloud config set compute/zone $GKE_ZONE

      - name: Setup Kubectl
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Deploy FastAPI-Clone-Docker-Image
        env:
          TLSINITIALKEY: ${{secrets.TLSINITIALKEY}}
          TLSINITIALCERT: ${{secrets.TLSINITIALCERT}}
          KIBANA_SERVER_URL: ${{secrets.KIBANA_SERVER_URL}}
          KIBANA_SECRET_TOKEN: ${{secrets.KIBANA_SECRET_TOKEN}}
        run: |
          helm upgrade --install fastapi-twitter-clone deployment/fastapi-twitter-clone \
            --set namespace="production-fastapi-twitter-clone" \
            --set certificates.tlsInitialKey="$TLSINITIALKEY" \
            --set certificates.tlsInitialCert="$TLSINITIALCERT" \
            --set kibana.KIBANA_SERVER_URL="$KIBANA_SERVER_URL" \
            --set kibana.KIBANA_SECRET_TOKEN="$KIBANA_SECRET_TOKEN" \
            --set kibana.KIBANA_ENVIRONMENT="PRODUCTION-K8S" \
            --set DNS.subDomainPrefix="production.twitter-clone" \
            --set deployment.TAG="$(echo $(python deployment/read_version.py))"


