# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
name: Test and Lint code

on:
  workflow_dispatch:
    inputs:
      python-version:
        required: false
        default: "3.11"
        description: "Python Version"
        type: string

  workflow_call:
    inputs:
      python-version:
        required: false
        default: "3.11"
        description: "Python Version"
        type: string

jobs:

  Linters:
    name: "Run Linters"
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: python-isort
        uses: isort/isort-action@v1.1.0

      - name: Black
        uses: psf/black@stable

      - name: Install flake8
        run: pip install flake8

      - name: Flake8 action
        uses: suo/flake8-github-action@v1
        with:
          checkName: Linters
