name: Deploy on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GCP_GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GCP_GKE_CLUSTER }}
  GKE_ZONE: us-central1-c


jobs:
  Lint-Code:
    uses: "./.github/workflows/Linting.yaml"
  Build-Docker-Image:
    uses: "./.github/workflows/Building.yaml"
    # Passing down secrets manually workarround
    # https://github.com/orgs/community/discussions/25238#discussioncomment-3247035
    secrets:
      GCP_IDENTITY_PROVIDER: ${{ secrets.GCP_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_GKE_PROJECT: ${{ secrets.GCP_GKE_PROJECT }}
      GCP_GKE_CLUSTER: ${{ secrets.GCP_GKE_CLUSTER }}
  Deploy-to-K8S:
    needs: Build-Docker-Image
    uses: "./.github/workflows/Deploy.yaml"
    secrets:
      GCP_IDENTITY_PROVIDER: ${{ secrets.GCP_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_GKE_PROJECT: ${{ secrets.GCP_GKE_PROJECT }}
      GCP_GKE_CLUSTER: ${{ secrets.GCP_GKE_CLUSTER }}
      KIBANA_SERVER_URL: ${{secrets.KIBANA_SERVER_URL}}
      KIBANA_SECRET_TOKEN: ${{secrets.KIBANA_SECRET_TOKEN}}